In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df.shape

(4340, 8)

In [3]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [4]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [5]:
df["name"].unique()

array(['Maruti 800 AC', 'Maruti Wagon R LXI Minor',
       'Hyundai Verna 1.6 SX', ..., 'Mahindra Verito 1.5 D6 BSIII',
       'Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV',
       'Hyundai i20 Magna 1.4 CRDi'], shape=(1491,), dtype=object)

In [6]:
df["name"].value_counts()

name
Maruti Swift Dzire VDI                  69
Maruti Alto 800 LXI                     59
Maruti Alto LXi                         47
Hyundai EON Era Plus                    35
Maruti Alto LX                          35
                                        ..
Hyundai Santro AT                        1
Hyundai Santro Xing XS eRLX Euro III     1
Honda Amaze S Petrol BSIV                1
Tata Indigo CS LS (TDI) BS-III           1
Volkswagen CrossPolo 1.2 MPI             1
Name: count, Length: 1491, dtype: int64

In [7]:
df['Car Age']=2026-df['year']

In [8]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,Car Age
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner,19
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner,19
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner,14
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner,9
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner,12
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner,12
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner,17
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner,10
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner,10

In [9]:
df.drop(['year'], axis=1, inplace=True)

In [10]:
df = df[df['selling_price'] < df['selling_price'].quantile(0.95)]

In [11]:
brand_mapping = {
    'Maruti': 'Maruti',
    'Hyundai': 'Hyundai',
    'Honda': 'Honda',
    'Toyota': 'Toyota',
    'Ford': 'Ford',
    'BMW': 'BMW',
    'Audi': 'Audi',
    'Volkswagen': 'Volkswagen',
    'Tata': 'Tata',
    'Mahindra': 'Mahindra',
    'Renault': 'Renault',
    'Nissan': 'Nissan',
    'Skoda': 'Skoda',
    'Chevrolet': 'Chevrolet',
    'Datsun': 'Datsun',
    'Jeep': 'Jeep',
    'Kia': 'Kia',
    'MG': 'MG',
    'Volvo': 'Volvo',
    'Jaguar': 'Jaguar',
    'Land': 'Land Rover',
    'Mercedes-Benz':'Mercedes',
    'Fiat':'Fiat',
    'Mitsubishi':'Mitsubishi',
    'Daewoo':'Daewoo',
    'Ambassador':'Ambassador',
    'OpelCorsa':'OpelCorsa',
    'Isuzu':'Isuzu',
    'Force':'Force'    
}

In [12]:
df['brand'] = df['name'].str.split().str[0].map(brand_mapping)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\4217742777.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['brand'] = df['name'].str.split().str[0].map(brand_mapping)

In [13]:
df['brand']

0        Maruti
1        Maruti
2       Hyundai
3        Datsun
4         Honda
         ...
4335    Hyundai
4336    Hyundai
4337     Maruti
4338    Hyundai
4339    Renault
Name: brand, Length: 4115, dtype: object

In [14]:
df

,name,selling_price,km_driven,fuel,seller_type,transmission,owner,Car Age,brand
0,Maruti 800 AC,60000,70000,Petrol,Individual,Manual,First Owner,19,Maruti
1,Maruti Wagon R LXI Minor,135000,50000,Petrol,Individual,Manual,First Owner,19,Maruti
2,Hyundai Verna 1.6 SX,600000,100000,Diesel,Individual,Manual,First Owner,14,Hyundai
3,Datsun RediGO T Option,250000,46000,Petrol,Individual,Manual,First Owner,9,Datsun
4,Honda Amaze VX i-DTEC,450000,141000,Diesel,Individual,Manual,Second Owner,12,Honda
...,...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),409999,80000,Diesel,Individual,Manual,Second Owner,12,Hyundai
4336,Hyundai i20 Magna 1.4 CRDi,409999,80000,Diesel,Individual,Manual,Second Owner,12,Hyundai
4337,Maruti 800 AC BSIII,110000,83000,Petrol,Individual,Manual,Second Owner,17,Maruti
4338,Hyundai Creta 1.6 CRDi SX Option,865000,90000,Diesel,Individual,Manual,First Owner,10,Hyundai
4339,Renault KWID RXT,225000,40000,Petrol,Individual,Manual,First Owner,10,Renault

In [15]:
df.isnull().sum()

name             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
Car Age          0
brand            0
dtype: int64

In [16]:
df.to_csv('car1.csv')

In [17]:
df.drop('name', axis=1, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\890587739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('name', axis=1, inplace=True)

In [18]:
df

,selling_price,km_driven,fuel,seller_type,transmission,owner,Car Age,brand
0,60000,70000,Petrol,Individual,Manual,First Owner,19,Maruti
1,135000,50000,Petrol,Individual,Manual,First Owner,19,Maruti
2,600000,100000,Diesel,Individual,Manual,First Owner,14,Hyundai
3,250000,46000,Petrol,Individual,Manual,First Owner,9,Datsun
4,450000,141000,Diesel,Individual,Manual,Second Owner,12,Honda
...,...,...,...,...,...,...,...,...
4335,409999,80000,Diesel,Individual,Manual,Second Owner,12,Hyundai
4336,409999,80000,Diesel,Individual,Manual,Second Owner,12,Hyundai
4337,110000,83000,Petrol,Individual,Manual,Second Owner,17,Maruti
4338,865000,90000,Diesel,Individual,Manual,First Owner,10,Hyundai
4339,225000,40000,Petrol,Individual,Manual,First Owner,10,Renault

In [19]:
from sklearn.preprocessing import LabelEncoder

for col in ['fuel', 'seller_type', 'transmission', 'owner', 'brand']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\1848494909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\1848494909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\1848494909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\1848494909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\1848494909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = le.fit_transform(df[col])

In [20]:
df

,selling_price,km_driven,fuel,seller_type,transmission,owner,Car Age,brand
0,60000,70000,4,1,1,0,19,12
1,135000,50000,4,1,1,0,19,12
2,600000,100000,1,1,1,0,14,10
3,250000,46000,4,1,1,0,9,5
4,450000,141000,1,1,1,2,12,9
...,...,...,...,...,...,...,...,...
4335,409999,80000,1,1,1,2,12,10
4336,409999,80000,1,1,1,2,12,10
4337,110000,83000,4,1,1,2,17,12
4338,865000,90000,1,1,1,0,10,10
4339,225000,40000,4,1,1,0,10,17

In [21]:
x = df.drop('selling_price', axis=1)
y = df['selling_price']

In [22]:
x

      km_driven  fuel  seller_type  transmission  owner  Car Age  brand
0         70000     4            1             1      0       19     12
1         50000     4            1             1      0       19     12
2        100000     1            1             1      0       14     10
3         46000     4            1             1      0        9      5
4        141000     1            1             1      2       12      9
...         ...   ...          ...           ...    ...      ...    ...
4335      80000     1            1             1      2       12     10
4336      80000     1            1             1      2       12     10
4337      83000     4            1             1      2       17     12
4338      90000     1            1             1      0       10     10
4339      40000     4            1             1      0       10     17

[4115 rows x 7 columns]

In [23]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4115, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [25]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [26]:
y_pred=model.predict(x_test)

In [27]:
from sklearn.metrics import r2_score, mean_absolute_error
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2 Score: 0.6829136823935269
MAE: 96885.64777466965

In [28]:
df['predicted_price'] = model.predict(x)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_15948\3477401651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['predicted_price'] = model.predict(x)

In [29]:
df

,selling_price,km_driven,fuel,seller_type,transmission,owner,Car Age,brand,predicted_price
0,60000,70000,4,1,1,0,19,12,63975.000000
1,135000,50000,4,1,1,0,19,12,130550.000000
2,600000,100000,1,1,1,0,14,10,541690.000000
3,250000,46000,4,1,1,0,9,5,248200.000000
4,450000,141000,1,1,1,2,12,9,451499.990000
...,...,...,...,...,...,...,...,...,...
4335,409999,80000,1,1,1,2,12,10,412243.190929
4336,409999,80000,1,1,1,2,12,10,412243.190929
4337,110000,83000,4,1,1,2,17,12,128061.606667
4338,865000,90000,1,1,1,0,10,10,862777.047500
4339,225000,40000,4,1,1,0,10,17,276772.311429

In [30]:
df.to_csv('data12.csv', index=False)

In [31]:
print(df['fuel'].value_counts())

fuel
4    2100
1    1951
0      40
3      23
2       1
Name: count, dtype: int64